# =====================================================
# Gradle 配置
# =====================================================

# JVM 参数
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Kotlin 代码风格
kotlin.code.style=official

# AndroidX
android.useAndroidX=true

# 并行构建
org.gradle.parallel=true

# 非传递性 R class
android.nonTransitiveRClass=true

# 强制使用系统 JDK
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-21.0.7.6-hotspot
org.gradle.java.installations.auto-download=true
org.gradle.java.installations.auto-detect=true
